version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voting-app
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - poll-net

  backend:
    build: ./votingapp
    container_name: poll-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/voting-app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8090:8090"
    networks:
      - poll-net

  frontend:
    build: ./poll-app
    container_name: poll-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - poll-net

networks:
  poll-net: